services:
  api:
    image: ghcr.io/gazes-media/mono-api:latest
    restart: always
    container_name: api-prod-gazes
    ports:
      - "3002:3002"
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@89.234.183.191:5432/${POSTGRES_DB}
      - PORT=3002
      - FIREBASE_PRIVATE_KEY=${FIREBASE_PRIVATE_KEY}

  proxy:
    image: ghcr.io/gazes-media/mono-proxy:latest
    restart: always
    container_name: proxy-prod-gazes
    ports:
      - "32770:2545"
    environment:
      - PORT=2545
      - PROXY_URL={PROXY_URL}
