services:
  api:
    image: api-gazes-prod
    restart: always
    build: ./apps/api
    container_name: api-prod-gazes
    ports:
      - "5300:5300"
    networks:
      - gazes
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@89.234.183.191:5432/${POSTGRES_DB}
      - REDIS_URL=redis://redis:6379
      - PORT=5300
      - FIREBASE_PRIVATE_KEY=${FIREBASE_PRIVATE_KEY}

  front:
    image: front-gazes-prod
    container_name: front-gazes-prod
    build: ./apps/front
    networks:
      - gazes
    ports:
      - "5454:3000"
    # Removed volumes for production to ensure the container is immutable
    depends_on:
      - api-prod-gazes
    environment:
      - API_URL=http://api-prod-gazes:5300
      - PROXY_URL=https://gazes.fr/proxy

networks:
  gazes:
    driver: bridge
