services:
  db:
    image: postgres:alpine
    restart: always
    container_name: postgres_gazes_dev
    networks:
      - gazes
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - gazes-db:/var/lib/postgresql/data

  api:
    image: api_gazes_dev
    restart: always
    build:
      context: ./apps/api
      dockerfile: dev.Dockerfile
    container_name: api_gazes_dev
    networks:
      - gazes
    volumes:
      - ./apps/api:/app
      - /app/node_modules
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      - REDIS_URL=redis://redis:6379
      - PORT=3002
      - FIREBASE_PRIVATE_KEY=${FIREBASE_PRIVATE_KEY}
    ports:
      - "3002" # Let Docker assign a random port

  front:
    image: front_gazes_dev
    container_name: front_gazes_dev
    build:
      context: ./apps/front
      dockerfile: dev.Dockerfile
    volumes:
      - ./apps/front/src:/app/src
      - ./apps/front/public:/app/public
    networks:
      - gazes
    depends_on:
      - api
    environment:
      - API_URL=http://api:5300
      - PROXY_URL=https://gazes.fr/proxy
    ports:
      - "3003" # Let Docker assign a random port

  proxy:
    image: proxy
    build: ./apps/proxy
    container_name: proxy_gazes
    ports:
      - "3004" # Let Docker assign a random port
    networks:
      - gazes
    depends_on:
      - front
    environment:
      - PORT=3004

  redis:
    image: redis
    restart: always
    container_name: redis_gazes
    networks:
      - gazes
    volumes:
      - gazes-redis:/data

networks:
  gazes:
    driver: bridge

volumes:
  gazes-db:
  gazes-redis:
